#!/bin/sh

filename=$(basename -- "$1")
extension="${filename##*.}"
filename="${filename%.*}"

python main.py $1 > "$filename.ll"
if [ $? != 1 ]
then
    llc "$filename.ll"
    clang "$filename.s" -o "$filename.exec"
fi
